version: '3.8'

services:
  atfot:
    image: ghcr.io/${{ github.repository_owner }}/atfot:latest  # Use pulled image, not build
    container_name: atfot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - atfot-data:/app/data
      - ./logs:/app/logs
      - ./resources:/app/resources
    networks:
      - atfot-net

volumes:
  atfot-data:

networks:
  atfot-net:
    driver: bridge