version: '3.8'

services:
  atfot:
    build: .
    container_name: atfot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - atfot-data:/app/data
      - ./logs:/app/logs
      - ./resources:/app/resources
    networks:
      - atfot-net

volumes:
  atfot-data:

networks:
  atfot-net:
    driver: bridge
